### ISSUE TITLE
Problem with update data in "Most users ever online"

### ISSUE THREAD

**Issue by leschek** [RobertHeim/phpbb3_1-ext-activitystats#15]
I reinstalled the extension with (master) update (I also deleted old extension data).
I set cache time to 0 s.
I reset most users ever online and deleted forum cache, so I can check when I have was some visitors on forum.
It's only testing forum with only a few visits, but Yahoo bot showed immediately in "Who is online" and in "Activity Stats" too.
A day after record in "Who is online" - 2 users I still have only 1 user in "Activity Stats" record.

**Comment by RobertHeim** [comment]
Hey, I re-wrote some parts of the session management. Can you check if the master branch fixes the issue for you guys?

**Comment by Galixte** [comment]
Hi,

i have the same problem with “Most users ever online” between phpBB stats and those of this extension. I have bump your topic on phpBB.com.

**Comment by Galixte** [comment]
Hi,

an answer from @rxu (Extension Team of phpBB.com): https://www.phpbb.com/community/viewtopic.php?p=14094836#p14094836

**Comment by RobertHeim** [comment]
Hi, and thank you Galixte for notification.
Can you guys test the current master branch? Hopefully the bug has been fixed.
=)

**Comment by Galixte** [comment]
Hi,

i will, come back later after tests. Thanks ;=)

**Comment by Galixte** [comment]
OK, after test from 2 days, this is my results:
From phpBB:
```
WHO IS ONLINE
In total there is 1 user online :: 1 registered, 0 hidden and 0 guests (based on users active over the past 1 minute)
Most users ever online was 8 on Mon 8 Jun 2015 à 11:55
```
From your extension:
```
ACTIVITY STATISTICS
The following data is based on users active over the past 24 hours.

New topics 0 • New posts 4 • New users 0
In total there were 68 users online :: 7 registered, 0 hidden, 5 bots and 56 guests
Most users ever online was 73 between Sun 7 Jun 2015 - 16:10 and Mon 8 Jun 2015 - 16:10
```

I think it’s not coherent, no ?

**Comment by RobertHeim** [comment]
Hi,

Thanks for data, stats seem fine to me. Why would you think it's not coherent?

Am 8. Juni 2015 19:56:24 MESZ, schrieb "Raphaël M." <notifications@github.com>:

**Comment by Galixte** [comment]
Hi,

now, i have always those stats on inex page:
```
WHO IS ONLINE
In total there are 2 users online :: 1 registered, 0 hidden and 1 guest (based on users active over the past 1 minute)
Most users ever online was 8 on Mon 8 Jun 2015 à 11:55
```

```
STATISTICS
Total posts 863 • Total topics 170 • Total members 43 • Our newest member daniel

ACTIVITY STATISTICS
The following data is based on users active over the past 24 hours.

New topics 1 • New posts 3 • New users 1
In total there were 67 users online :: 6 registered, 0 hidden, 6 bots and 55 guests
Most users ever online was 73 between Sun 7 Jun 2015 - 16:10 and Mon 8 Jun 2015 - 16:10
```

In ACP i use the “Displaying users of ...:” option with “Period of Time” set to 24 hours.

Why i don’t have a message like that: 
```
Most users ever online was XX between Sun 8 Jun 2015 - 16:10 and Mon 9 Jun 2015 - 16:10
```

I think it’s not correct because, yesterday, the message from your extension said this:
```
ACTIVITY STATISTICS
The following data is based on users active over the past 24 hours.

New topics 0 • New posts 4 • New users 0
In total there were 68 users online :: 7 registered, 0 hidden, 5 bots and 56 guests
Most users ever online was 73 between Sun 7 Jun 2015 - 16:10 and Mon 8 Jun 2015 - 16:10
```

If the total of users online were of 68 why the most ever online was to 73. The total can’t be inferior of most users ever online.

**Comment by RobertHeim** [comment]
Hi

I think u misunderstood the terms:

total users = count of users online in current configured timespan, e.g. last 24h.

Most users ever online = record of total users.

So most users ever online should always be greater or equal to total users.

So your data seems to be fine: 73 > 68

Greets

Am 9. Juni 2015 18:14:53 MESZ, schrieb "Raphaël M." <notifications@github.com>:

**Comment by Galixte** [comment]
OK, i understand now, but why this value of your extension is opposed to the “Most users ever online” from phpBB in “WHO IS ONLINE” ?

NOTE: Both statistics were reset at the same time, there are two days.

**Comment by RobertHeim** [comment]
The wording is the same as in phpbb.

Am 10. Juni 2015 01:52:44 MESZ, schrieb "Raphaël M." <notifications@github.com>:

**Comment by Galixte** [comment]
Yes but not the values.

**Comment by RobertHeim** [comment]
Yes, the values are different, because the extension does not calculate 
the same data as phpbb.. otherwise we would not need the extension ;)
Activity Stats calculates the user session data based on another 
timespan than phpbb. That is what the AS statistics are about!
E.g. in your data the phpbb data is based on 1 Minute. The AS are based 
on 24 hours. Of course there are more users online within 24 hours than 
in 1 minute.

Am 10.06.2015 um 14:11 schrieb Raphaël M.:

**Comment by RobertHeim** [comment]
As there were I consider this ticket closed, as there were not any more feedback after the last fix.
