### ISSUE TITLE
Permission tab in ACP

### ISSUE THREAD

**Issue by Galixte** [RobertHeim/phpbb3_1-ext-activitystats#32]
Hi,

since that i have activate your extension, in ACP it's impossble to go in permission tab.

**Comment by RobertHeim** [comment]
what happens if you disable it? and which language do you use?

**Comment by RobertHeim** [comment]
oh and did you update or fresh install the extension?

**Comment by Galixte** [comment]
Hi,

Hi,my default language on my board is FRENCH.

My user language is FRENCH.

I have ENGLISH language installed too.

If i disable this extension, the permission tab works normally.

And it's a fresh install v1.2.4-DEV the lastest.

**Comment by RobertHeim** [comment]
what do you mean by "impossble to go in permission tab."? Whitescreen? What does the server error-log say?

**Comment by RobertHeim** [comment]
maybe its because your server does not support mb_strtoupper

**Comment by RobertHeim** [comment]
can you pls update and try again?

**Comment by Galixte** [comment]
yes, the page is a Whitescreen

**Comment by Galixte** [comment]
always a white screen after update

**Comment by RobertHeim** [comment]
I think phpbb requires mb-extension oft PHP. Can you make sure that it is installed on your server?

**Comment by Galixte** [comment]
Based on this page : http://www.2by2host.com/articles/php-errors-faq/disabled_mb_strtoupper/

i have searched in php.ini any occurrence who mentioned mb_strtoupper but nothing

**Comment by RobertHeim** [comment]
I think mbstring is fine in this phpinfo. What does the Server error log files say?

**Comment by Galixte** [comment]
Log : ezcom-fr.com-access.log

```
2a01:e35:39c8:3f0:a5e0:a5bf:8ce5:9e50 - - [02/Mar/2015:00:46:42 +0100] "GET /adm/index.php?sid=2469e6c3c85a40f039d8573c2fba95e6&i=12 HTTP/1.1" 200 3690
2a01:e35:39c8:3f0:a5e0:a5bf:8ce5:9e50 - - [02/Mar/2015:00:46:45 +0100] "GET /adm/index.php?sid=2469e6c3c85a40f039d8573c2fba95e6&i=21 HTTP/1.1" 200 5554
2a01:e35:39c8:3f0:a5e0:a5bf:8ce5:9e50 - - [02/Mar/2015:00:46:49 +0100] "GET /adm/index.php?sid=2469e6c3c85a40f039d8573c2fba95e6&i=16 HTTP/1.1" 500 222
2a01:e35:39c8:3f0:a5e0:a5bf:8ce5:9e50 - - [02/Mar/2015:00:47:47 +0100] "GET /adm/index.php?sid=2469e6c3c85a40f039d8573c2fba95e6&i=16 HTTP/1.1" 500 222
```

**Comment by RobertHeim** [comment]
That is the access log but we need the error log.

**Comment by Galixte** [comment]
Aucun erreurs mentionnées dans: ezcom-fr.com-error.log

**Comment by Galixte** [comment]
Ok, if i switch to english language for my admin user, the permissions tab works good

**Comment by Galixte** [comment]
It's this file who is the problem : /ext/robertheim/activitystats/language/fr/permissions_activitystats.php

**Comment by Galixte** [comment]
OK i found : https://github.com/Galixte/phpbb3_1-ext-activitystats/commit/1667c751b849f611c3865d5689ba9f9ee18a9fad

my PR contains this fix + my update for FRENCH language translation : https://github.com/RobertHeim/phpbb3_1-ext-activitystats/pull/31
