### ISSUE TITLE
The input area for date formats don’t accept accented characters

### ISSUE THREAD

**Issue by Galixte** [RobertHeim/phpbb3_1-ext-activitystats#36]
Hi @RobertHeim,

in ACP if i want to input a character accented in two area for date formats they appears with ???.

**Comment by RobertHeim** [comment]
I don't understand your description. Can you give an example?

**Comment by RobertHeim** [comment]
Do you mean the "Dateformat" option? Make sure it conforms to the php-date format: http://php.net/manual/en/function.date.php

**Comment by Galixte** [comment]
Hi,

thanks and sorry for my explanation.
