### ISSUE TITLE
Displaying users of X years for periode time

### ISSUE THREAD

**Issue by Galixte** [RobertHeim/phpbb3_1-ext-activitystats#41]
Hi @RobertHeim,

is it possible to set 10 years or more for the period time by using the “Days” parameter, like this: `3650`(or more) ?

I have an old phpBB 2.0.x board which has the stats the number of visitors (More than 1 500 000 since 10 years). I would update this forum to 3.1.x branch of phpBB and to continue to display this stat.

**Comment by RobertHeim** [comment]
Hi,
I would not suggest doing so. This extension safes session data for the length of the period. What you want is another extension that just counts the overall visitors oft the board.

Am 21. August 2015 05:27:31 MESZ, schrieb "Raphaël M." notifications@github.com:

**Comment by Galixte** [comment]
Ok, thanks.
